Variables;

[x, fval] = BIC_fam_sellmarket(no_aq, ...
                               no_fish_market_thres, ...
                               cost_repop, ...
                               utility_cost_per_cycle, ...
                               cost_labor_market, ...
                               price_fish_mark, ...
                               price_fish_comm, ...
                               cost_investaq, ...
                               labor_cost_sell_comm, ...
                               no_fish_system, ...
                               fish_death_rate, ...
                               BIC_growth, ...
                               min_family_fish_eat,...
                               fish_market_sell_fraction,...
                               no_fam_market);
protein = [fval, transpose(x)];
                           
disp('       n1       n2       n3        n4         n5        n6');
disp(protein(2:end));
disp(['Fish within the community at the end of a growth cycle: ', num2str(protein(1))]);